### PR TITLE
Dockerize project

### LINKED ISSUE #78: Dockerize the project
We should Dockerize the project to have a easy way to distribute a demo that would be easy to run locally.

I know of a couple of people that are interested in something like horas for their local community and I think that a container is another attractive way to have people try it.

### PR DESCRIPTION
**Pull request by froi**
Hey guys!

These changes resolve #78. They aren't yet complete but I figured that starting to look at them wouldn't hurt.

IMO the changes that are left is to get Brunch working and update the README with a Docker section.

Thoughts?

### CODE REVIEW

**Comment by froi** [comment]
Decided not to get brunch working in the container. I'd rather add some volumes and have the user execute the commands on his local machine. This will keep the image simpler and smaller in size.

Having a volume will make developing with the image better. You won't have to constantly copy the source to the container.

**Comment by jpadilla** [comment]
Hablando de brunch, I vote for @gcollazo to switch all that for a nicer setup with webpack.

**Comment by froi** [comment]
@jpadilla Sure. Let's create a new issue with that. I wouldn't do it here.

**Comment by gcollazo** [comment]
Yeah yo puedo hacer eso.

**Comment by froi** [comment]
@jpadilla @gcollazo can you guys give this a look before we merge. Thanks!

**Pull request merged**
